# ==========================================
# QuantKos: Exaples configuration
# Params from pag 212, F.Rouah, The Heston Model and its Extensions in Matlab and C#
# ==========================================
Market:
  Price: 8.0    # Initial asset price (S0) (spot price)
  Variance: 0.0625  # Initial variance (v0)
  r: 0.1       # Risk-free interest rate
  q: 0.0        # Continuous dividend yield

Options:
  OptionType: Asian #American
  OptionRight: Put
  StrikePrice: 10.

Model:
  Heston:
    k: 5.0        # Mean reversion speed of the variance (kappa)
    theta: 0.16   # Long-term mean of the variance
    sigma: 0.9    # Volatility of the variance (vol-of-vol)
    rho: 0.1     # Correlation between price and variance Brownian motions

Numerics:
  Scheme: ImplicitMilstein   # Available schemes: Euler, ImplicitMilstein, AndersonQE ...

Time:
  T_End: 0.25      # Time to maturity (in years)
  Inp_DT: 0.00025   # Time step size in years (dt)

MC:
  Normalize_prices : true # If true, it normalizes monetary parameters relative to S0 (if false, keeps everything untouched).
  N_Paths: 1000000 # Number of Monte Carlo realizations/paths
  Batch_Size: 0 # Number of paths run in parallel before saving (0 means auto-computed based on hardware)
  RNG_Seed: 88471920573105
  Max_VRAM_MB: 256 #512 #2048 # Max Available VRAM (Default 256 MB)
  Max_CPU_RAM_MB: 6000 #8000 Max Available RAM

Output:
  out_dir: "" #"./install/outputs"
  Name_Paths_Out_File: "" # "temp.paths" # QuantKosPaths.paths
  Name_Log_File: "" #"QuantKos.log"
  Format: BIN     # Available formats: TXT, BIN