# ==========================================
# TESTS
# ==========================================
run_tests:
   - AmericanOption
  # - Bates
  # - BlackScholes
  # - Heston
  #- IOBin
  #- NoNoise
  #- RNG

