var searchData=
[
  ['q_0',['q',['../structquantkos_1_1Config_1_1MarketConfig.html#ac74b00470e7a7452bbcbc3306bdff395',1,'quantkos::Config::MarketConfig']]],
  ['qkos_5fbuild_5ftype_1',['QKOS_BUILD_TYPE',['../namespaceCMakeLists.html#a56af379b8066228fb0bde07d40cbd0e4',1,'CMakeLists']]],
  ['quantkos_2',['quantkos',['../index.html#autotoc_md92',1,'▶️ Running QuantKos'],['../md_COMPILATION__GUIDE.html#autotoc_md29',1,'3. Install QuantKos'],['../md_COMPILATION__GUIDE.html#autotoc_md36',1,'5. Run QuantKos'],['../namespacequantkos.html',1,'quantkos'],['../md_COMPILATION__GUIDE.html#autotoc_md30',1,'Step 1: Download QuantKos'],['../md_COMPILATION__GUIDE.html#autotoc_md31',1,'Step 2: Build QuantKos'],['../md_COMPILATION__GUIDE.html#autotoc_md34',1,'Step 3: Install QuantKos']]],
  ['quantkos_20_3a_20math_20guide_3',['QuantKos : Math Guide',['../md_MATH__GUIDE.html',1,'']]],
  ['quantkos_3a_20compilation_20guide_4',['QuantKos: Compilation Guide',['../md_COMPILATION__GUIDE.html',1,'']]],
  ['quantkos_3a_20performance_20portable_20monte_20carlo_20option_20pricing_20engine_5',['QuantKos: Performance-Portable Monte Carlo Option Pricing Engine',['../index.html',1,'']]],
  ['quantkos_3a_20user_20input_20guide_6',['QuantKos: User Input Guide',['../md_USER__INPUT__GUIDE.html',1,'']]],
  ['quantkos_3a_3aconfig_7',['Config',['../namespacequantkos_1_1Config.html',1,'quantkos']]],
  ['quantkos_3a_3aengine_8',['Engine',['../namespacequantkos_1_1Engine.html',1,'quantkos']]],
  ['quantkos_3a_3aengine_3a_3aanalytical_9',['Analytical',['../namespacequantkos_1_1Engine_1_1Analytical.html',1,'quantkos::Engine']]],
  ['quantkos_3a_3aengine_3a_3aanalytical_3a_3abates_10',['Bates',['../namespacequantkos_1_1Engine_1_1Analytical_1_1Bates.html',1,'quantkos::Engine::Analytical']]],
  ['quantkos_3a_3aengine_3a_3aanalytical_3a_3ablackscholes_11',['BlackScholes',['../namespacequantkos_1_1Engine_1_1Analytical_1_1BlackScholes.html',1,'quantkos::Engine::Analytical']]],
  ['quantkos_3a_3aengine_3a_3aanalytical_3a_3aheston_12',['Heston',['../namespacequantkos_1_1Engine_1_1Analytical_1_1Heston.html',1,'quantkos::Engine::Analytical']]],
  ['quantkos_3a_3aengine_3a_3alsm_13',['LSM',['../namespacequantkos_1_1Engine_1_1LSM.html',1,'quantkos::Engine']]],
  ['quantkos_3a_3ahelp_14',['HELP',['../namespacequantkos_1_1HELP.html',1,'quantkos']]],
  ['quantkos_3a_3aimplemented_15',['Implemented',['../namespacequantkos_1_1Implemented.html',1,'quantkos']]],
  ['quantkos_3a_3aio_16',['IO',['../namespacequantkos_1_1IO.html',1,'quantkos']]],
  ['quantkos_3a_3aio_3a_3abinary_17',['Binary',['../namespacequantkos_1_1IO_1_1Binary.html',1,'quantkos::IO']]],
  ['quantkos_3a_3akeys_18',['Keys',['../namespacequantkos_1_1Keys.html',1,'quantkos']]],
  ['quantkos_3a_3akeys_3a_3amarketparams_19',['MarketParams',['../namespacequantkos_1_1Keys_1_1MarketParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3amathmodelparams_20',['MathModelParams',['../namespacequantkos_1_1Keys_1_1MathModelParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3amcparams_21',['MCParams',['../namespacequantkos_1_1Keys_1_1MCParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3anumschemeparams_22',['NumSchemeParams',['../namespacequantkos_1_1Keys_1_1NumSchemeParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3aoptionsparams_23',['OptionsParams',['../namespacequantkos_1_1Keys_1_1OptionsParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3aoutparams_24',['OutParams',['../namespacequantkos_1_1Keys_1_1OutParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3akeys_3a_3atimeparams_25',['TimeParams',['../namespacequantkos_1_1Keys_1_1TimeParams.html',1,'quantkos::Keys']]],
  ['quantkos_3a_3atests_26',['Tests',['../namespacequantkos_1_1Tests.html',1,'quantkos']]],
  ['quantkos_3a_3atests_3a_3abates_27',['Bates',['../namespacequantkos_1_1Tests_1_1Bates.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3ablackscholes_28',['BlackScholes',['../namespacequantkos_1_1Tests_1_1BlackScholes.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3agreeks_29',['Greeks',['../namespacequantkos_1_1Tests_1_1Greeks.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3aheston_30',['Heston',['../namespacequantkos_1_1Tests_1_1Heston.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3aiobin_31',['IOBIN',['../namespacequantkos_1_1Tests_1_1IOBIN.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3alsm_32',['LSM',['../namespacequantkos_1_1Tests_1_1LSM.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3anonoise_33',['NoNoise',['../namespacequantkos_1_1Tests_1_1NoNoise.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3arng_34',['RNG',['../namespacequantkos_1_1Tests_1_1RNG.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atests_3a_3autils_35',['Utils',['../namespacequantkos_1_1Tests_1_1Utils.html',1,'quantkos::Tests']]],
  ['quantkos_3a_3atypes_36',['Types',['../namespacequantkos_1_1Types.html',1,'quantkos']]],
  ['quantkosbuilder_37',['QuantKosBuilder',['../classbuilder_1_1QuantKosBuilder.html',1,'builder']]],
  ['quarter_5fsigma_5fsq_5fdt_38',['quarter_sigma_sq_dt',['../structquantkos_1_1Engine_1_1SDEScheme_3_01KI_1_1MathModel_1_1Heston_00_01KI_1_1NumScheme_1_1ImplicitMilstein_01_4.html#a9daa66d76cd3c1f274616dd2722d024a',1,'quantkos::Engine::SDEScheme&lt; KI::MathModel::Heston, KI::NumScheme::ImplicitMilstein &gt;']]],
  ['query_20your_20gpu_20compute_20capability_39',['Step 3.1: Query Your GPU Compute Capability',['../md_COMPILATION__GUIDE.html#autotoc_md22',1,'']]],
  ['quick_20start_40',['🚀 Quick Start',['../index.html#autotoc_md81',1,'']]]
];
