var searchData=
[
  ['c_0',['C',['../structquantkos_1_1Engine_1_1LSM_1_1Coeffs.html#aa6b1e85ee1b6997fcc7211315d9679f0',1,'quantkos::Engine::LSM::Coeffs']]],
  ['c_20dependencies_1',['C. Dependencies',['../md_COMPILATION__GUIDE.html#autotoc_md5',1,'']]],
  ['c_20gpu_20profiling_20suite_20nvidia_20nsight_2',['C. GPU Profiling Suite (NVIDIA Nsight)',['../md_COMPILATION__GUIDE.html#autotoc_md9',1,'']]],
  ['c_3a_20gpu_20accelerated_20cuda_20release_3',['Option C: GPU Accelerated (CUDA / Release)',['../md_COMPILATION__GUIDE.html#autotoc_md20',1,'']]],
  ['call_4',['Call',['../namespacequantkos_1_1Implemented.html#a114c027448b76520d405547c3a2fddd3ac3755e61202abd74da5885d2e9c9160e',1,'quantkos::Implemented']]],
  ['capability_5',['Step 3.1: Query Your GPU Compute Capability',['../md_COMPILATION__GUIDE.html#autotoc_md22',1,'']]],
  ['capability_20to_20the_20kokkos_20flag_6',['Step 3.2: Match Your Compute Capability to the Kokkos Flag',['../md_COMPILATION__GUIDE.html#autotoc_md24',1,'']]],
  ['carlo_7',['Monte Carlo',['../md_USER__INPUT__GUIDE.html#autotoc_md112',1,'']]],
  ['carlo_20engine_8',['Monte Carlo Engine',['../index.html#autotoc_md76',1,'']]],
  ['carlo_20option_20pricing_20engine_9',['QuantKos: Performance-Portable Monte Carlo Option Pricing Engine',['../index.html',1,'']]],
  ['cash_20or_20nothing_10',['Cash-or-Nothing',['../md_MATH__GUIDE.html#autotoc_md65',1,'']]],
  ['characteristics_11',['Performance Characteristics',['../namespacequantkos_1_1IO_1_1Binary.html#autotoc_md44',1,'']]],
  ['clone_20the_20repository_12',['Clone the repository',['../index.html#autotoc_md81',1,'']]],
  ['cmakelists_13',['CMakeLists',['../namespaceCMakeLists.html',1,'']]],
  ['cmakelists_2etxt_14',['cmakelists.txt',['../tests_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../src_2CMakeLists_8txt.html',1,'(Global Namespace)'],['../CMakeLists_8txt.html',1,'(Global Namespace)'],['../app_2CMakeLists_8txt.html',1,'(Global Namespace)']]],
  ['code_20documentation_20setup_15',['6.5 CODE Documentation Setup',['..//home/runner/work/QuantKos/QuantKos/CMakeLists.txt#doc_sec',1,'']]],
  ['coeffs_16',['Coeffs',['../structquantkos_1_1Engine_1_1LSM_1_1Coeffs.html',1,'quantkos::Engine::LSM']]],
  ['command_20line_20help_17',['Displaying the Command-Line Help',['../md_COMPILATION__GUIDE.html#autotoc_md37',1,'']]],
  ['common_20market_20parameters_18',['Common Market Parameters',['../md_MATH__GUIDE.html#autotoc_md47',1,'']]],
  ['compare_5fnumerical_5fand_5fexpected_5foption_5fprice_19',['compare_numerical_and_expected_option_price',['../namespacequantkos_1_1Tests_1_1Utils.html#aa7e2d8e918ec0460eddd8acd2882a264',1,'quantkos::Tests::Utils']]],
  ['compilation_20guide_20',['QuantKos: Compilation Guide',['../md_COMPILATION__GUIDE.html',1,'']]],
  ['compilation_5fguide_2emd_21',['COMPILATION_GUIDE.md',['../COMPILATION__GUIDE_8md.html',1,'']]],
  ['compiler_20sdk_22',['Step 2 (Required): Install GPU Toolchain (CUDA Compiler &amp; SDK)',['../md_COMPILATION__GUIDE.html#autotoc_md12',1,'']]],
  ['complex_23',['complex',['../namespacequantkos_1_1Engine_1_1Analytical_1_1Heston.html#aaa7d8ddce30360f64dfbec1a224dbb56',1,'quantkos::Engine::Analytical::Heston::Complex'],['../namespacequantkos_1_1Engine_1_1Analytical_1_1Bates.html#ad36b265b7ba434b58e2878de908bc273',1,'quantkos::Engine::Analytical::Bates::Complex']]],
  ['compute_20capability_24',['Step 3.1: Query Your GPU Compute Capability',['../md_COMPILATION__GUIDE.html#autotoc_md22',1,'']]],
  ['compute_20capability_20to_20the_20kokkos_20flag_25',['Step 3.2: Match Your Compute Capability to the Kokkos Flag',['../md_COMPILATION__GUIDE.html#autotoc_md24',1,'']]],
  ['compute_5fregression_5fsums_5fon_5fdevice_26',['compute_regression_sums_on_device',['../classquantkos_1_1Engine_1_1LSM_1_1LSMEngine.html#a01153fe8f0587f2d66febbf577dcd3f9',1,'quantkos::Engine::LSM::LSMEngine']]],
  ['config_2ehpp_27',['Config.hpp',['../Config_8hpp.html',1,'']]],
  ['config_5ferr_5fmsg_28',['config_err_msg',['../namespacequantkos_1_1Config.html#aff388fa040087b3c283df72526d16ad5',1,'quantkos::Config']]],
  ['configfileenums_2ehpp_29',['ConfigFileEnums.hpp',['../ConfigFileEnums_8hpp.html',1,'']]],
  ['configfilekeys_2ehpp_30',['ConfigFileKeys.hpp',['../ConfigFileKeys_8hpp.html',1,'']]],
  ['configfilekeysenummaps_2ehpp_31',['ConfigFileKeysEnumMaps.hpp',['../ConfigFileKeysEnumMaps_8hpp.html',1,'']]],
  ['configparser_2ecpp_32',['ConfigParser.cpp',['../ConfigParser_8cpp.html',1,'']]],
  ['configuration_33',['configuration',['../index.html#autotoc_md91',1,'⚙️ Simulation Configuration'],['../md_USER__INPUT__GUIDE.html#autotoc_md115',1,'2. Automated Test Configuration'],['../namespaceCMakeLists.html#release_sec',1,'6. Production Release Optimization Configuration'],['../namespaceCMakeLists.html#reldeb_sec',1,'6.5 Profiling Optimization Configuration']]],
  ['configuration_20file_34',['1. Simulation Configuration File',['../md_USER__INPUT__GUIDE.html#autotoc_md104',1,'']]],
  ['configurations_35',['6. Debug Mode Configurations',['../namespaceCMakeLists.html#debug_sec',1,'']]],
  ['configure_20a_20release_20build_36',['Configure a Release build',['../index.html#autotoc_md83',1,'']]],
  ['configure_20the_20build_37',['2. Configure the Build',['../md_COMPILATION__GUIDE.html#autotoc_md27',1,'']]],
  ['configure_20the_20environment_38',['Configure the Environment',['../md_COMPILATION__GUIDE.html#autotoc_md13',1,'']]],
  ['contracts_39',['contracts',['../index.html#autotoc_md74',1,'Supported Option Contracts'],['../md_MATH__GUIDE.html#autotoc_md53',1,'Supported Option Contracts']]],
  ['contributing_40',['🤝 Contributing',['../index.html#autotoc_md99',1,'']]],
  ['copy_5fcurrent_5fmc_5fbatch_5fto_5fmaster_5fmc_5fmatrix_41',['copy_current_mc_batch_to_master_mc_matrix',['../classquantkos_1_1Engine_1_1BackwardLSMMemory.html#a123cbfed3e40a4cda17068ebb6259e53',1,'quantkos::Engine::BackwardLSMMemory']]],
  ['core_20build_20tools_42',['A. Core Build Tools',['../md_COMPILATION__GUIDE.html#autotoc_md3',1,'']]],
  ['core_20cpu_20openmp_20release_43',['Option B: Multi-Core CPU (OpenMP / Release)',['../md_COMPILATION__GUIDE.html#autotoc_md19',1,'']]],
  ['core_20parameters_44',['Core Parameters',['../md_MATH__GUIDE.html#autotoc_md51',1,'']]],
  ['core_20release_45',['Option A: Procedural Single Core (Release)',['../md_COMPILATION__GUIDE.html#autotoc_md18',1,'']]],
  ['core_20utilities_20documentation_20tools_46',['Step 1 (Required): Install Core Utilities &amp; Documentation Tools',['../md_COMPILATION__GUIDE.html#autotoc_md11',1,'']]],
  ['cores_20openmp_20builds_47',['Running on Multiple CPU Cores (OpenMP builds)',['../md_COMPILATION__GUIDE.html#autotoc_md39',1,'']]],
  ['count_48',['count',['../structquantkos_1_1Engine_1_1LSM_1_1RegressionSums.html#abd23cc7c3295a148bb3b5673baaa38d9',1,'quantkos::Engine::LSM::RegressionSums']]],
  ['cpp_49',['Step 4 (Recommended): Download, Build and Install yaml-cpp',['../md_COMPILATION__GUIDE.html#autotoc_md25',1,'']]],
  ['cpu_20cores_20openmp_20builds_50',['Running on Multiple CPU Cores (OpenMP builds)',['../md_COMPILATION__GUIDE.html#autotoc_md39',1,'']]],
  ['cpu_20openmp_20release_51',['Option B: Multi-Core CPU (OpenMP / Release)',['../md_COMPILATION__GUIDE.html#autotoc_md19',1,'']]],
  ['cpu_20threads_20or_20gpus_20optional_52',['Specifying CPU Threads or GPUs (Optional)',['../md_COMPILATION__GUIDE.html#autotoc_md38',1,'']]],
  ['create_20a_20build_20directory_53',['Create a build directory',['../index.html#autotoc_md82',1,'']]],
  ['cuda_20builds_54',['Running on NVIDIA GPUs (CUDA builds)',['../md_COMPILATION__GUIDE.html#autotoc_md40',1,'']]],
  ['cuda_20compiler_20sdk_55',['Step 2 (Required): Install GPU Toolchain (CUDA Compiler &amp; SDK)',['../md_COMPILATION__GUIDE.html#autotoc_md12',1,'']]],
  ['cuda_20release_56',['Option C: GPU Accelerated (CUDA / Release)',['../md_COMPILATION__GUIDE.html#autotoc_md20',1,'']]]
];
