#pragma once

#include <fstream>
#include <string>
#include <stdexcept>
#include <filesystem>

#include <Kokkos_Core.hpp>

#include "./../core/config/Config.hpp"
#include "./../core/config/ConfigFileEnums.hpp"
#include "./IOBlueprints.hpp"
#include "../core/memory/PathsMCBatchMem.hpp"
#include "./../core/Typedefs.hpp"


namespace KOps::IO::Binary {
    namespace KC = KOps::Config;
    namespace KI = KOps::Implemented;
    namespace KT = KOps::Types;
    namespace KIO = KOps::IO;

    // ========================================================================
    // SINGLE SOURCE OF TRUTH: BINARY FORMAT LAYOUT
    // ========================================================================
    /**
     * @brief Fixed metadata header placed at the absolute beginning of the saved binary files.
     * * This layout acts as an ID card for the file. It allows any reader to instantly verify
     * that the binary data is valid, was generated by KOptions, and uses the correct number
     * format precision (float vs. double) before loading the actual path matrix payload.
     */
    struct BinHeader {
        const char file_key[4] = {'K', 'O', 'P', 'T'}; ///< File signature key to identify valid KOptions files.
        int version = 1; ///< File format version number for potential future compatibility checks.
        int byte_precision = sizeof(KT::Real); ///< Precision size (4 for 32-bit float, 8 for 64-bit double).
        int total_n_sims; ///< Total number of simulation paths stored in this file.
        int n_time_steps; ///< Discrete time steps simulated per path.
        KT::Real dt; ///< The size of each time step (dt) to reconstruct the uniform time grid.
    };

    // ========================================================================
    // THE BINARY WRITER RESPONSIBLE
    // ========================================================================
    /**
     * @brief High-performance file writer that serializes simulated asset price paths to disk in binary format.
     * * Saves raw memory directly to disk. This is much faster and uses far less storage space than writing
     * numbers as human-readable text files (like CSV or TXT).
     * * The writer automatically handles two writing pathways:
     * 1. **The Fast Track (Contiguous)**: If the device memory layout is contiguous (and with layout right), it writes the entire batch
     * to disk in a single, ultra-fast block transfer instruction.
     * 2. **The Buffered Fallback**: If the layout is fragmented, it safely gathers the scattered prices
     * row-by-row into a temporary buffer before writing them to disk.
     */
    class BinWriter : public KIO::WriterBlueprint {
    public:
        /**
         * @brief Constructs the writer and opens the target output binary file writing the header.
         * @param conf Reference to the master configurations tree.
         * @throw std::runtime_error If the system fails to create directories or open the file stream.
         * @note Automatically sets up the folders, opens a binary output stream, and writes the
         * file metadata header block (`BinHeader`) to disk first.
         */
        explicit BinWriter(const Config::UInputs &conf) : config(conf) {
            // Create paths buffer if needed
            if (!config.output.filename_paths_out.empty()) {
                full_paths_out_path = std::filesystem::path(config.output.out_dir) / config.output.filename_paths_out;

                out_paths_stream.open(full_paths_out_path.string(), std::ios::out | std::ios::binary);
                if (!out_paths_stream.is_open()) {
                    throw std::runtime_error(
                        "[BinWriter Error] Failed to open binary output file: " + full_paths_out_path.string());
                }
                write_global_header();
            }
        }

        /// @name Lifecycle & Resource Ownership Rules
        ///@{
        BinWriter(const BinWriter &) = delete; ///< Copy constructor is deleted to protect file writer streams.
        BinWriter &operator=(const BinWriter &) = delete; ///< Copy assignment is also deleted.
        BinWriter(BinWriter &&) = delete; ///< Move constructor is deleted.
        BinWriter &operator=(BinWriter &&) = delete; ///< Move assignment is deleted.
        /**
         * @brief Closes the active file handle if it is still open on destruction.
         */
        ~BinWriter() override {
            if (out_paths_stream.is_open()) out_paths_stream.close();
        }

        ///@}

        /**
         * @brief Writes an active batch of path prices directly to the open binary stream.
         * @param current_batch_size Number of active paths in the current execution batch.
         * @param BatchMem Buffer allocation structure containing the batch path data.
         */
        void save_paths_batch_if_needed(int current_batch_size, const Engine::PathsMCBatchMem &BatchMem) override {
            // Return without writing if no file is specified
            if (config.output.filename_paths_out.empty()) {
                return;
            }

            //Calculate exactly how many bytes this specific batch occupies (N_sims x n_t_steps x sizeReal)
            // This is flexible and allows to consider cases where the batch is not complete
            const size_t bytes_to_write = static_cast<size_t>(current_batch_size) *
                                          static_cast<size_t>(config.time.N_time_steps) * sizeof(KT::Real);

            // Fetch the raw C-style pointer from the Kokkos Host View
            const KT::Real *raw_data_ptr = BatchMem.h_batch_view.data();

            // SCENARIO A: The Fast Track (Only runs if the layout is physically contiguous and layout right)
            if (BatchMem.is_host_contiguous() && BatchMem.is_host_row_major()) {
                // Dump it to the SSD in one hardware instruction
                out_paths_stream.write(reinterpret_cast<const char *>(raw_data_ptr), bytes_to_write);
            }

            // SCENARIO B: The Universal Buffered Fallback
            else {
                // 1. Allocate a contiguous memory buffer for exactly one row
                std::vector<KT::Real> row_buffer(config.time.N_time_steps);
                const size_t row_bytes = config.time.N_time_steps * sizeof(KT::Real);

                // Loop through row-by-row
                for (int i = 0; i < current_batch_size; ++i) {
                    // 2. Read the scattered RAM data (whatever layout it is) into our clean buffer
                    for (size_t j = 0; j < config.time.N_time_steps; ++j) {
                        row_buffer[j] = BatchMem.h_batch_view(i, j);
                    }

                    // 3. Dump the ENTIRE ROW to the SSD in exactly one hardware instruction
                    out_paths_stream.write(reinterpret_cast<const char *>(row_buffer.data()), row_bytes);
                }
            }
        }


        /**
         * @brief Prints a clean summary layout of the binary file structure to the standard console.
         */
        void print_planned_outputs_summary() const override {
            constexpr std::string_view indent = "  ";
            std::cout << "\n" << indent << "========================================================\n";
            std::cout << indent << "               BINARY I/O WRITER PERFORMANCE            \n";
            std::cout << indent << "========================================================\n";

            if (!config.output.filename_paths_out.empty()) {
                std::cout << indent << "   Export Format        :  High-Performance Binary\n";
                std::cout << indent << "--------------------------------------------------------\n";
                std::cout << indent << " [Binary File Layout Structure]\n";
                std::cout << indent << "   |-- GLOBAL HEADER (" << sizeof(BinHeader) << " Bytes)\n";
                std::cout << indent << "   |   |-- Magic Key    : 'KOPT' (4 bytes)\n";
                std::cout << indent << "   |   |-- Version      : 1 (int32)\n";
                std::cout << indent << "   |   |-- Precision    : " << sizeof(KT::Real) <<
                        " bytes per value (int32)\n";
                std::cout << indent << "   |   |-- Total Paths  : " << config.mc.N_Paths << " (int32)\n";
                std::cout << indent << "   |   |-- Time Steps   : " << config.time.N_time_steps << " (int32)\n";
                std::cout << indent << "   |   |-- Time dt      : " << config.time.dt << " (float64)\n";
                std::cout << indent << "   |\n";
                std::cout << indent << "   |-- MATRIX PAYLOAD\n";
                std::cout << indent << "       |-- Dimensions   : " << config.mc.N_Paths << " rows x " << config.
                        time.N_time_steps << " cols\n";
                std::cout << indent << "       |-- Ordering     : Row-Major (C-Style Sequential)\n";
                std::cout << indent << "       |-- Contents     : Price time series\n";
            } else {
                std::cout << indent << "  No output files will be written (filename empty).\n";
            }
            std::cout << indent << "========================================================\n" << std::endl;
        }

    private
    :
        const KC::UInputs &config; ///< Reference to master user parameters tree.
        std::ofstream out_paths_stream; ///< Output file stream handle.
        std::filesystem::path full_paths_out_path; ///< Absolute disk output path.

        /**
         * @brief Builds and serializes the header metadata structure to the beginning of the file.
         */
        void write_global_header() {
            // 1. Setup Header Data
            BinHeader header;
            header.total_n_sims = config.mc.N_Paths;
            header.n_time_steps = config.time.N_time_steps;
            header.dt = config.time.dt;

            // 2. Dump Header Struct directly to disk
            // reinterpret_cast forces the compiler to treat the memory address as an array of raw, unsigned bytes (const char*).
            out_paths_stream.write(reinterpret_cast<const char *>(&header), sizeof(BinHeader));
        }
    };


    // ========================================================================
    // THE BINARY READER RESPONSIBLE
    // ========================================================================
    /**
     * @brief High-performance file reader that loads price path data from saved binary files.
     * @note Instead of loading massive files entirely into memory, it uses mathematical stride equations to
     * "jump" directly to specific columns in the file, extracting only the price slice needed.
     */
    class BinReader : public KIO::ReaderBlueprint {
    public:
        /**
         * @brief Constructs the reader and loads the header of the specified paths file.
         * @param conf Reference to the master simulation configurations containing file paths.
         */
        explicit BinReader(const Config::UInputs &conf) : config(conf) {
            if (!config.output.filename_paths_out.empty()) {
                load_header_paths_file();
            }
        }

        // Should implement move constructor (Transfers the file handle safely)!?
        /// @name Lifecycle & Resource Ownership Rules
        ///@{
        BinReader(const BinReader &) = delete; ///< Copy constructor is deleted to protect open reader handles.
        BinReader &operator=(const BinReader &) = delete; ///< Copy assignment is also deleted.
        BinReader(BinReader &&) = delete; ///< Move constructor is deleted.
        BinReader &operator=(BinReader &&) = delete; ///< Move assignment is deleted.
        /**
         * @brief Closes the active file handle if open on destruction.
         */
        ~BinReader() override {
            if (inp_stream.is_open()) inp_stream.close();
        }

        ///@}

        /**
         * @brief Extracts the cross-sectional spot prices across all simulated paths at a target timeline coordinate.
         * @note Automatically translates the continuous time request (e.g., $t = 0.5$ years) into the closest
         * discrete time-step index, checks system boundaries, and reads the targeted prices directly from disk.
         * * @param current_time The target timeline coordinate in years (e.g., 1.5).
         * @return A standard vector containing the loaded spot prices at that time across all paths.
         * @throw std::runtime_error If the file stream is closed, if the requested time falls outside
         * of the simulated timeline, or if the request does not align with the discrete time step (dt).
         */
        std::vector<KT::Real> read_prices_at_target_time(double current_time) override {
            if (!inp_stream.is_open()) {
                throw std::runtime_error("[BinReader Error] Cannot read prices, file stream is closed.");
            }

            // Map continuous time to discrete index (a row major layour is assumed)
            int target_col_idx = static_cast<int>(std::round(current_time / bin_header.dt)) - 1;
            // Check That required time is in time domain
            if (target_col_idx < 0 || target_col_idx >= bin_header.n_time_steps) {
                throw std::runtime_error("[BinReader Error] Requested time " + std::to_string(current_time) +
                                         " is outside the simulated time grid bounds.");
            }
            // Check that the required time is in the time grid and do not required interpolation
            double actual_grid_time = (target_col_idx + 1) * bin_header.dt;
            if (std::abs(current_time - actual_grid_time) > 1e-10) {
                throw std::runtime_error("Requested time  " + std::to_string(current_time) +
                                         " does not align perfectly with the discrete simulation grid (dt = " +
                                         std::to_string(bin_header.dt) + ")."
                );
            }

            // Allocate the vector containing the prices at target times
            std::vector<KT::Real> target_prices(bin_header.total_n_sims);

            // Calculate the memory strides
            std::streampos start_offset_bytes = sizeof(BinHeader) + (target_col_idx * sizeof(KT::Real));
            //Absolute location in a file from beginning
            std::streamoff row_stride_bytes = bin_header.n_time_steps * sizeof(KT::Real);
            // jumping of a simulation (relative distance)

            // Read Prices
            for (int i = 0; i < bin_header.total_n_sims; ++i) {
                // Calculate absolute byte position for this specific element by adding a relative distance (streamoff) to the starting point
                std::streampos element_pos = start_offset_bytes + (static_cast<std::streamoff>(i) * row_stride_bytes);
                // Jump to the exact byte location on the disk (Start measuring the element position from beginning of the file)
                inp_stream.seekg(element_pos, std::ios::beg);
                // Read exactly one floating point number into our vector
                inp_stream.read(reinterpret_cast<char *>(&target_prices[i]), sizeof(KT::Real));
            }

            // Clear any EOF flags that might have triggered, allowing future reads
            inp_stream.clear();

            return target_prices;
        }

    private:
        const KC::UInputs &config; ///< Reference to master configurations tree.
        BinHeader bin_header; ///< Local container representing the loaded file metadata parameters.
        std::ifstream inp_stream; ///< Input file stream handle.

        /**
         * @brief Loads the header of the binary path file and validates the magic keys and precision types.
         * @throw std::runtime_error If the file fails to open, if the file signature does not match "KOPT",
         * or if the file was saved with a different numeric precision than the compiled system.
         */
        void load_header_paths_file() {
            // Open File Paths
            auto file_out_paths = std::filesystem::path(config.output.out_dir) / config.output.filename_paths_out;
            inp_stream.open(file_out_paths.string(), std::ios::in | std::ios::binary);
            if (!inp_stream.is_open()) {
                throw std::runtime_error("[BinReader Error] Failed to open file: " + file_out_paths.string());
            }
            // Read header
            inp_stream.read(reinterpret_cast<char *>(&bin_header), sizeof(BinHeader));
            // Check if heaser is ok
            if (bin_header.file_key[0] != 'K' || bin_header.file_key[1] != 'O' ||
                bin_header.file_key[2] != 'P' || bin_header.file_key[3] != 'T') {
                throw std::runtime_error(
                    "[BinReader Error] Magic key mismatch. File is corrupted or not a KOptions.paths file.");
            }
            if (bin_header.byte_precision != sizeof(KT::Real)) {
                throw std::runtime_error(
                    "[BinReader Error] Build precision mismatch. Data cannot safely map into target system precision.");
            }
        }
    };
}
